(function () {
  if (!window.i18next) {
    const langKey = 'apple-site-language'; const codes = { 'zh-CN': 'zh-CN', 'zh-TW': 'zh-TW', en: 'en' }; const bundles = {}; let current = localStorage.getItem(langKey) || 'zh-CN';
    const t = (key, vars) => { const value = (bundles[current] && bundles[current][key]) ?? (bundles['zh-CN'] && bundles['zh-CN'][key]) ?? key; return String(value).replace(/{{\s*([^}]+)\s*}}/g, (_, name) => vars?.[name] ?? ''); };
    const render = () => { document.documentElement.lang = current; document.querySelectorAll('[data-i18n]').forEach((el) => { el.textContent = t(el.dataset.i18n); }); document.querySelectorAll('[data-i18n-attr]').forEach((el) => el.dataset.i18nAttr.split(',').forEach((pair) => { const [attr,key] = pair.split(':').map((x) => x.trim()); if (attr && key) el.setAttribute(attr, t(key)); })); document.title = t(location.pathname.includes('/products') ? 'title.products' : location.pathname.includes('/support') ? 'title.support' : location.pathname.includes('/privacy') ? 'title.privacy' : location.pathname.includes('/values') ? 'title.values' : location.pathname.includes('/iphone') ? 'title.iphone' : location.pathname.includes('/mac') ? 'title.mac' : location.pathname.includes('/ipad') ? 'title.ipad' : location.pathname.includes('/watch') ? 'title.watch' : location.pathname.includes('/airpods') ? 'title.airpods' : 'site.title'); document.dispatchEvent(new CustomEvent('i18n:rendered')); };
    window.i18next = { t, getLanguage: () => current, changeLanguage: async (next) => { current = codes[next] || next || 'zh-CN'; localStorage.setItem(langKey, current); render(); return current; }, renderPage: render, locales: bundles };
    window.t = t;
    const base = document.currentScript?.src?.replace(/preferences\.js.*$/, '') || './';
    Promise.all(Object.values(codes).map(async (code) => { try { const response = await fetch(`${base}locales/${code}.json`); bundles[code] = await response.json(); } catch { bundles[code] = {}; } })).then(render);
  }
  const motionKey = 'apple-site-motion';
  const languageCode = () => window.i18next?.getLanguage?.() || localStorage.getItem('apple-site-language') || 'zh-CN';
  const motionEnabled = () => localStorage.getItem(motionKey) !== 'off';
  const label = (key, fallback) => window.t ? window.t(key) : fallback;
  const applyMotion = () => document.documentElement.classList.toggle('motion-off', !motionEnabled());
  const host = document.querySelector('.nav-actions,.global-nav,.info-nav');
  if (!host || host.querySelector('.preference-button')) { applyMotion(); return; }
  const style = document.createElement('style');
  style.textContent = `.site-preference-actions,.preference-actions{display:flex;align-items:center;gap:2px;margin-left:4px}.preference-button{appearance:none;border:0;background:transparent;color:inherit;display:grid;place-items:center;min-width:34px;height:34px;padding:0 8px;border-radius:17px;cursor:pointer;font-size:11px;line-height:1;transition:background-color .2s,color .2s}.preference-button:hover,.preference-button:focus-visible{background:rgba(0,0,0,.07);color:#0071e3}.preference-panel{position:fixed;top:58px;right:18px;z-index:120;width:230px;padding:8px;background:rgba(250,250,252,.96);border:1px solid rgba(0,0,0,.1);border-radius:14px;box-shadow:0 16px 45px rgba(0,0,0,.16);backdrop-filter:blur(22px);opacity:0;visibility:hidden;transform:translateY(-6px);transition:opacity .2s,transform .2s,visibility .2s}.preference-panel.open{opacity:1;visibility:visible;transform:none}.preference-panel-title{margin:5px 10px 7px;color:#6e6e73;font-size:11px}.language-option{display:flex;align-items:center;justify-content:space-between;width:100%;min-height:38px;padding:0 10px;border:0;border-radius:8px;background:transparent;color:#1d1d1f;text-align:left;font-size:13px;cursor:pointer}.language-option:hover,.language-option:focus-visible{background:#e8e8ed}.language-option[aria-current=true]{color:#0071e3;font-weight:600}.language-option[aria-current=true]::after{content:'✓'}.preference-divider{height:1px;margin:7px 10px;background:rgba(0,0,0,.1)}.motion-row{display:flex;align-items:center;justify-content:space-between;padding:5px 10px 7px;color:#1d1d1f;font-size:13px}.motion-switch{position:relative;width:38px;height:22px;border:0;border-radius:11px;background:#c7c7cc;cursor:pointer}.motion-switch:after{content:'';position:absolute;top:3px;left:3px;width:16px;height:16px;border-radius:50%;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.25);transition:transform .2s}.motion-switch[aria-pressed=true]{background:#34c759}.motion-switch[aria-pressed=true]:after{transform:translateX(16px)}.motion-off *,.motion-off *:before,.motion-off *:after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}@media(max-width:800px){.preference-panel{top:54px;right:12px}.preference-button{min-width:31px;padding:0 5px}}`;
  document.head.append(style);
  const actions = document.createElement('div'); actions.className = host.classList.contains('nav-actions') ? 'site-preference-actions' : 'preference-actions';
  actions.innerHTML = `<button class="preference-button" type="button" data-preference="language" aria-label="${label('common.chooseLanguage', '选择语言')}" aria-expanded="false">中</button><button class="preference-button" type="button" data-preference="motion" aria-label="${label('common.motion', '动态效果')}" aria-pressed="${motionEnabled()}">◌</button>`; host.append(actions);
  const panel = document.createElement('div'); panel.className = 'preference-panel'; panel.setAttribute('aria-hidden','true'); panel.innerHTML = '<p class="preference-panel-title"></p><div class="language-options"></div><div class="preference-divider"></div><div class="motion-row"><span class="motion-label"></span><button class="motion-switch" type="button"></button></div>'; document.body.append(panel);
  const languageButton = actions.querySelector('[data-preference=language]'); const motionButton = actions.querySelector('[data-preference=motion]'); const motionSwitch = panel.querySelector('.motion-switch');
  const renderPanel = () => { const lang = languageCode(); languageButton.textContent = lang === 'en' ? 'EN' : lang === 'zh-TW' ? '繁' : '中'; languageButton.setAttribute('aria-label', label('common.chooseLanguage','选择语言')); panel.querySelector('.preference-panel-title').textContent = lang === 'en' ? 'Language' : lang === 'zh-TW' ? '語言' : '语言'; panel.querySelector('.language-options').innerHTML = [['zh-CN','language.zhCN'],['zh-TW','language.zhTW'],['en','language.en']].map(([code,key]) => `<button class="language-option" type="button" data-language="${code}" aria-current="${lang === code}">${label(key, code)}</button>`).join(''); const enabled = motionEnabled(); const motionLabel = label(enabled ? 'common.motionOff' : 'common.motionOn', enabled ? '关闭动态效果' : '开启动态效果'); motionButton.setAttribute('aria-label', motionLabel); motionSwitch.setAttribute('aria-label', motionLabel); motionSwitch.setAttribute('aria-pressed', String(enabled)); panel.querySelector('.motion-label').textContent = label('common.motion','动态效果'); };
  const close = () => { panel.classList.remove('open'); panel.setAttribute('aria-hidden','true'); languageButton.setAttribute('aria-expanded','false'); };
  languageButton.addEventListener('click', (event) => { event.stopPropagation(); renderPanel(); const open = !panel.classList.contains('open'); panel.classList.toggle('open', open); panel.setAttribute('aria-hidden', String(!open)); languageButton.setAttribute('aria-expanded', String(open)); });
  motionButton.addEventListener('click', (event) => { event.stopPropagation(); localStorage.setItem(motionKey, motionEnabled() ? 'off' : 'on'); applyMotion(); renderPanel(); });
  panel.addEventListener('click', async (event) => { const option = event.target.closest('[data-language]'); if (!option) return; await window.i18next?.changeLanguage(option.dataset.language); renderPanel(); close(); });
  document.addEventListener('click', (event) => { if (!panel.contains(event.target) && !actions.contains(event.target)) close(); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') close(); }); document.addEventListener('i18n:rendered', renderPanel); renderPanel(); applyMotion();
})();
